#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  >&2 echo "Usage: $0 <author>"
  exit 1
fi

AUTHOR=$1
AUTHOR_NAME=$(echo $AUTHOR | perl -wlne '/^(.*?)\s*<.*>$/ and print $1')
AUTHOR_EMAIL=$(echo $AUTHOR | perl -wlne '/^.*\s*<(.*)>$/ and print $1')

{
  for BRANCH in $(git branch | tr -d " *"); do
    git checkout -b $BRANCH
    for COMMIT in $(git log --oneline | cut -b 1-7); do
      GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/edit $COMMIT/'" git rebase -i $COMMIT~1^^ 
      GIT_COMMITTER_NAME="$AUTHOR_NAME" GIT_COMMITTER_EMAIL="$AUTHOR_EMAIL" git commit --amend --no-edit --author="$AUTHOR"
      git rebase --continue
    done
  done
} &> /dev/null

echo "$AUTHOR_NAME is now the author of THE ENTIRE REPOSITORY. You're officially an asshole (and deserves a one-way ticket to hell).";
